---
version: "2.1"
services:
  dokuwiki:
    image: linuxserver/dokuwiki
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - APP_URL=/dokuwiki #optional
    volumes:
      - /path/to/volume/dokuwiki:/config
    ports:
      - 8080:80
      - 8443:443 #optional
    restart: unless-stopped

